### ISSUE TITLE
Weird error when trying to use `pretrends`

### ISSUE THREAD

**Issue by dklinenberg2020** [jonathandroth/pretrends#1]
Hello,

Thank you for creating this package (and more importantly the econometric contributions). I loaded in your `pretrends` package and `slope_for_power` worked awesome, but I got this weird error for `pretrends`:

```
Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/Library/Frameworks/R.framework/Versions/4.1/Resources/library/gmm/libs/gmm.so':
  dlopen(/Library/Frameworks/R.framework/Versions/4.1/Resources/library/gmm/libs/gmm.so, 6): Library not loaded: /usr/local/gfortran/lib/libgomp.1.dylib
  Referenced from: /Library/Frameworks/R.framework/Versions/4.1/Resources/library/gmm/libs/gmm.so
  Reason: image not found
```

For reference, my code looks like this:

```
mod1<-fixest::feols(log(amount_usd+1)~ev_cat|channel+as.factor(date),
                    cluster = "channel",
                    data = dat %>% 
                      # filter(!(channel %in% zero_peeps)) %>% 
                      mutate(ev_cat=as.factor(ev),
                             ev_cat=relevel(ev_cat, ref = "-1")#,
                             #amount_usd=log(amount_usd+1)
                      )
) 

sigma<-mod1$cov.unscaled
sigma<-mod1$coeftable[,2]
beta<-mod1$coeftable[,1]
tvec<-as.numeric(gsub("ev_cat","",names(mod1$coeftable[,1])
)
)
reference_period<--1
# looking at what he looks at
data.frame("t"=as.numeric(gsub("ev_cat","",names(mod1$coeftable[,1])
                               )
                          ),
           "beta"=mod1$coeftable[,1]
           )

slope50 <-
  slope_for_power(sigma = sigma,
                  targetPower = 0.5,
                  tVec = tvec,
                  referencePeriod = reference_period)
slope50

pretrendsResults <- 
  pretrends(betahat = beta, 
            sigma = sigma, 
            tVec = tvec, 
            referencePeriod = reference_period,
            deltatrue = slope50 * (tvec - reference_period))

```

Any help would be appreciated! Thank you for your time.

**Comment by jonathandroth** [comment]
Sorry to hear about this problem! This sounds like an R package installation problem. Sometimes re-starting R (and possibly reinstalling the package) can help. If not, this thread might help: https://stackoverflow.com/questions/21333097/got-message-unable-to-load-shared-object-stats-so-when-r-starts

If you google "error in dyn.load" there are many stackoverflow results describing this issue for various packages; it seems to be an R installation issue rather than a package-specific problem. 

Please let me know if any of those links is helpful!

**Comment by jonathandroth** [comment]
PS this help page has a suggestion precisely for the gmm package which seems to be at issue here. Let me know if that helps.
https://stackoverflow.com/questions/63511986/error-package-or-namespace-load-failed-for-gmm-in-dyn-loadfile-dllpath-dl

**Comment by dklinenberg2020** [comment]
Hello Jonathan,

So after a little fiddling, I figured out the issue was with missing fortran. If someone else runs into this issue, you need to download fortran and everything works great. I followed the link and everything works great!

Thanks again for your help.
